In [85]:
import torch
from torch.autograd import Variable
import numpy as np

a = torch.Tensor(128, 1, 512)
b = a.repeat(2, 5, 1)
print(b.shape)

x = torch.tensor([1, 2, 3])
xnew = x.repeat(1,3)
print(xnew)

x = torch.tensor([1, 2, 3])
xnew = x.repeat(3,1)
print(xnew)

tensor = torch.FloatTensor([[1, 2], [3, 4]])
print(tensor)

tensor_mean = torch.mean(tensor * tensor)
print(tensor_mean)

torch.Size([256, 5, 512])
tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3]])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
tensor([[1., 2.],
        [3., 4.]])
tensor(7.5000)


In [100]:
x = torch.randn(2, 3, 5) 
print('x.size: ', x.size()) 

print('x.permute(2, 0, 1).size(): ', x.permute(2, 0, 1).size())

a=np.array([[[1,2,3],[4,5,6]]])
unpermuted=torch.tensor(a)
print(unpermuted)
print('unpermuted.size: ', unpermuted.size())     #  ——>  torch.Size([1, 2, 3])

permuted=unpermuted.permute(2,0,1)
print('permuted.size: ', permuted.size())         #  ——>  torch.Size([3, 1, 2])

view_test = unpermuted.view(1,3,2)
print('view_test.size: ', view_test.size())     

x.size:  torch.Size([2, 3, 5])
x.permute(2, 0, 1).size():  torch.Size([5, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]]])
unpermuted.size:  torch.Size([1, 2, 3])
permuted.size:  torch.Size([3, 1, 2])
view_test.size:  torch.Size([1, 3, 2])


In [135]:
torch.manual_seed(1)

x = torch.randn(2,3)

y = torch.randn(1,3)

print(x)
print(y)

torch.cat((x,y),0)


tensor([[ 0.6614,  0.2669,  0.0617],
        [ 0.6213, -0.4519, -0.1661]])
tensor([[-1.5228,  0.3817, -1.0276]])


tensor([[ 0.6614,  0.2669,  0.0617],
        [ 0.6213, -0.4519, -0.1661],
        [-1.5228,  0.3817, -1.0276]])

In [184]:
A = torch.ones(2,3)
B = 2*torch.ones(4,3)#4x3的张量（矩阵）
C=torch.cat((A,B), 0)
print(C)
D = 2*torch.ones(2,4) #2x4的张量（矩阵）
C = torch.cat((A,D), 1)
print(C)
C = torch.cat((A,D), dim=1)
print(C)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[1., 1., 1., 2., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2., 2.]])
tensor([[1., 1., 1., 2., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2., 2.]])


In [185]:
# 定义Variable, requires_grad用来指定是否需要计算梯度
variable = Variable(tensor, requires_grad = True)
print(variable)

# 计算x^2的均值
variable_mean = torch.mean(variable * variable)
print(variable_mean)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor(7.5000, grad_fn=<MeanBackward0>)


In [186]:
# variable进行反向传播
# 梯度计算如下：
# variable_mean = 1/4 * sum(variable * variable)
# d(variable_mean)/d(variable) = 1/4 * 2 * variable = 1/2 * variable
variable_mean.backward()

# 输出variable中的梯度
print(variable.grad)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [187]:
# *表示逐元素点乘,不是矩阵乘法
print(tensor * tensor)
print(variable * variable)
print(variable.data)

tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor([[ 1.,  4.],
        [ 9., 16.]], grad_fn=<MulBackward0>)
tensor([[1., 2.],
        [3., 4.]])


In [188]:
# 然后定义pytorch中的tensor 并将tensor转化成Variable的形式
x_tensor = torch.FloatTensor([1, 2, 3])
print('张量的类型以及具体值:\n', type(x_tensor), x_tensor)
x_var = Variable(x_tensor, requires_grad = True)
print('变量的类型以及具体的值:\n', type(x_var), x_var)


张量的类型以及具体值:
 <class 'torch.Tensor'> tensor([1., 2., 3.])
变量的类型以及具体的值:
 <class 'torch.Tensor'> tensor([1., 2., 3.], requires_grad=True)


In [189]:
# 显示的调用pytorch中的反向传播

h = 2 * x_var / 3 * 2
print('\nh: ', h, h.grad_fn)
h.backward(torch.FloatTensor([3, 5, 7]))
print('\nh.backward: ', x_var, x_var.grad, x_var.grad_fn)



h:  tensor([1.3333, 2.6667, 4.0000], grad_fn=<MulBackward0>) <MulBackward0 object at 0x12c1613d0>

h.backward:  tensor([1., 2., 3.], requires_grad=True) tensor([4.0000, 6.6667, 9.3333]) None


In [190]:
# 显示的调用pytorch中的反向传播
y = x_var + 1
h = x_var + 2

y.backward(torch.FloatTensor([2, 2, 2]))
print('\ny：', y, '\n', y.grad_fn)
print('\nx_var：', x_var.grad, '\n', x_var.grad_fn)

print('\nh：', h, '\n', h.grad_fn)
h.backward(torch.FloatTensor([2, 2, 2]))
print('\nx_var：', x_var.grad, '\n', x_var.grad_fn)


y： tensor([2., 3., 4.], grad_fn=<AddBackward0>) 

x_var： tensor([ 6.0000,  8.6667, 11.3333]) 
 None

h： tensor([3., 4., 5.], grad_fn=<AddBackward0>) 

x_var： tensor([ 8.0000, 10.6667, 13.3333]) 
 None
